config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "users/registrations" }, path: "", path_names: { sign_in: "signin", signup: "signup", sign_out: "signout" }

  devise_scope :user do
    unauthenticated do
      root 'users/registrations#new'
    end

    authenticated :user do
      root 'days#show', as: :auth_root
    end

    # Users
    get 'signup', to: 'users/registrations#new', as: :signup
    post 'signup', to: 'users/registrations#create'
    get 'edit-user', to: redirect('/settings')
    patch 'edit-user', to: 'users/registrations#update'
    delete 'delete-account', to: 'users/registrations#destroy', as: :delete_account

    # Auth
    get 'signin', to: 'devise/sessions#new', as: :signin
    post 'signin', to: 'devise/sessions#create'
    delete 'signout', to: 'devise/sessions#destroy', as: :signout
  end

  # Diary
  resources :days, only: [:index, :create]
  get ':date', to: 'days#show', as: :day, date: /(\d|-){8,10}/
  get 'today', to: 'days#show', as: :today

  resources :diary_entries, except: [:show, :new]
  get 'edit-diary', to: 'diary_entries#index', as: :edit_diary

  resources :day_entries, only: [:update]

  # Pages
  get 'about', to: 'pages#about', as: :about
  get 'settings', to: 'pages#settings', as: :settings
  get 'check-email', to: 'pages#check_email', as: :check_email

end

app/views/layouts/shared/_errors.html.haml
- if object.errors.any?
  %ul.errors
    - object.errors.full_messages.each do |message|
      %li= message

app/views/layouts/shared/_flash.html.haml
- flash.each do |name, message|
  = message

app/views/layouts/shared/_footer.html.haml
%footer.page-footer
  .container 
    .row 
      .footer-copyright
        Designed by&nbsp;#{ link_to "Tony K.", "https://www.linkedin.com/in/tonykhay", target: "_blank" }

app/views/layouts/shared/_mobile_nav.html.haml
#mobile-nav.hide-on-med-and-up.fixed-action-btn
  %a#mobile-nav-button.btn-floating.btn-large{ name: "menu" }
    = material_icon.menu.md_24

  %ul
    - nav_buttons.each do |nav|
      %li
        = link_to nav[:url], id: nav[:id], name: nav[:name], class: "btn-floating waves-effect waves-light #{nav[:class]} tooltipped", data: { tooltip: "#{nav[:tooltip]}", position: "left" } do
          - if nav[:image]
            = nav[:image]
          - else
            = material_icon.send("#{nav[:icon]}")

app/views/layouts/shared/_nav.html.haml
#main-nav.hide-on-small-only
  - nav_buttons.each do |nav|
    = link_to nav[:url], id: nav[:id], name: nav[:name], class: "btn-floating btn-large waves-effect waves-light #{nav[:class]} tooltipped", data: { tooltip: "#{nav[:tooltip]}", position: "left" } do
      = material_icon.send("#{nav[:icon]}").md_24

app/views/layouts/shared/_navbar.html.haml
.navbar-fixed
  %nav{ id: block_id }
    .nav-wrapper
      - if user_signed_in?
        = link_to settings_path, id: "settings-button", name: "settings", class: "btn-large btn-floating halfway-fab tooltipped hide-on-small-only blue base", data: { tooltip: "Settings", position: "left" } do
          = user_icon(@current_user)
      .container
        .row
          = yield