config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "users/registrations" }, path: "", path_names: { sign_in: "signin", signup: "signup", sign_out: "signout" }

  devise_scope :user do
    unauthenticated do
      root 'users/registrations#new'
    end

    authenticated :user do
      root 'days#show', as: :auth_root
    end

    # Users
    get 'signup', to: 'users/registrations#new', as: :signup
    post 'signup', to: 'users/registrations#create'
    get 'edit-user', to: redirect('/settings')
    patch 'edit-user', to: 'users/registrations#update'
    delete 'delete-account', to: 'users/registrations#destroy', as: :delete_account

    # Auth
    get 'signin', to: 'devise/sessions#new', as: :signin
    post 'signin', to: 'devise/sessions#create'
    delete 'signout', to: 'devise/sessions#destroy', as: :signout
  end

  # Diary
  resources :days, only: [:index, :create]
  get ':date', to: 'days#show', as: :day, date: /(\d|-){8,10}/
  get 'today', to: 'days#show', as: :today

  resources :diary_entries, except: [:show, :new]
  get 'edit-diary', to: 'diary_entries#index', as: :edit_diary

  resources :day_entries, only: [:update]

  # Pages
  get 'about', to: 'pages#about', as: :about
  get 'settings', to: 'pages#settings', as: :settings
  get 'check-email', to: 'pages#check_email', as: :check_email

end

app/models/diary_entry.rb
class DiaryEntry < ApplicationRecord

  # title, sort_order, entry_type

  ENTRY_TYPES = %w(EntryText EntryCheck EntryLine)

  belongs_to :diary
  has_many :day_entries, dependent: :destroy

  validates :title, presence: true, uniqueness: { scope: :diary }, length: { maximum: 255 }
  validates :entry_type, presence: true, inclusion: { in: ENTRY_TYPES, message: "%{value} is not a valid entry type" }

  default_scope { order("sort_order ASC") }

  scope :reverse_ordered, -> { reorder("sort_order DESC") }
  scope :persisted, -> { where("id IS NOT NULL") }

  after_create :create_day_entries, :set_order

  protected

  def create_day_entries
    days = self.diary.days
    days.each do |day|
      self.day_entries.create(day: day)
    end
  end

  def set_order
    total_entries = self.diary.diary_entries.count
    self.update(sort_order: total_entries)
  end

end

app/controllers/diary_entries_controller.rb
class DiaryEntriesController < ApplicationController

  before_action :set_diary_entry, only: [:edit, :update, :destroy]

  def index
    @diary_entry = DiaryEntry.new
  end

  def create
    @diary_entry = @diary.diary_entries.new(diary_entry_params)
    if @diary_entry.save
      flash[:notice] = "Diary entry created."
      redirect_to edit_diary_path
    else
      render :index, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @diary_entry.update(diary_entry_params)
      flash[:notice] = "Diary entry updated."
      redirect_to edit_diary_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @diary_entry.destroy
    flash[:notice] = "Diary entry deleted."
    redirect_to edit_diary_path
  end

  private

  def set_diary_entry
    @diary_entry = @diary.diary_entries.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to edit_diary_path
  end

  def diary_entry_params
    params.require(:diary_entry).permit(:title, :entry_type, :sort_order, :hidden)
  end

end

app/helpers/diary_entry_helper.rb
module DiaryEntryHelper

  def toggled_class(entry, value)
    "toggled" if entry.entry_type == value
  end

end

app/views/diary_entries/_form.html.haml
-# TODO: implement errors processing
= render "layouts/shared/errors", object: @diary_entry

= form_with model: @diary_entry, local: true do |form|
  .row.input-field
    .col.title-field
      = form.text_field :title, placeholder: "Title"
    .col.actions

      .type-radio.radio-icons.left
        %label.tooltipped{ id: "entry-text-button", data: { tooltip: "Rich text area", position: "bottom" } }
          = form.radio_button :entry_type, "EntryText"
          %span{ class: toggled_class(@diary_entry, "EntryText") }
            = material_icon.insert_chart.r90
        %label.tooltipped{ id: "entry-check-button", data: { tooltip: "Check box", position: "bottom" } }
          = form.radio_button :entry_type, "EntryCheck"
          %span{ class: toggled_class(@diary_entry, "EntryCheck") }
            = material_icon.check_box
        %label.tooltipped{ id: "entry-line-button", data: { tooltip: "Short text box", position: "bottom" } }
          = form.radio_button :entry_type, "EntryLine"
          %span{ class: toggled_class(@diary_entry, "EntryLine") }
            = material_icon.font_download.css_class("normalize")

      .submit.right
        - if @diary_entry.new_record?
          %button.btn.waves-effect.waves-light.tooltipped{ id: "add-entry-button",  type: "submit", data: { tooltip: "Add entry", position: "bottom" } }
            = material_icon.add
        - else
          %button.btn.waves-effect.waves-light.tooltipped{ id: "save-entry-button", type: "submit", data: { tooltip: "Save entry", position: "bottom" } }
            = material_icon.save

  - unless @diary_entry.new_record?
    .row.advanced-actions

      .col.hidden.left
        .switch.tooltipped{ data: { tooltip: "Hide from your diary", position: "bottom" } }
          %label
            Hidden
            = form.check_box :hidden
            %span.lever

      .col.delete.left
        = link_to diary_entry_path(@diary_entry), method: :delete, data: { confirm: "Are you sure? This action cannot be undone. You can hide this entry instead.", tooltip: "Delete permanently", position: "bottom" }, class: "tooltipped" do
          %label Delete
          = material_icon.delete_forever

app/views/diary_entries/edit.html.haml
%header
  = render "layouts/shared/navbar", block_id: "edit-diary-navbar" do
    %span.nav-title Edit Entry

%main#edit-diary.edit-entry
  .container
    .row
      .col.s12.m11.l12.xl10.offset-xl1
        = render "form"

app/views/diary_entries/index.html.haml
%header
  = render "layouts/shared/navbar", block_id: "edit-diary-navbar" do
    %span.nav-title Edit Diary

%main#edit-diary
  .container
    .row
      .col.s12.m11.l12.xl10.offset-xl1
        - if @diary_entries.present?
          .diary-entries
            - @diary_entries.each do |entry|

              .input-field.diary-entry{ class: ("hidden tooltipped" if entry.hidden?), data: ({ tooltip: "This entry is hidden from your diary", position: "bottom" } if entry.hidden?) }
                .left.valign-wrapper
                  = material_icon.short_text.css_class("prefix")
                  %span.title= entry.title

                .right.valign-wrapper
                  - if entry.entry_type == "EntryText"
                    .tip-icon
                      = material_icon.insert_chart.r90
                  - elsif entry.entry_type == "EntryCheck"
                    .tip-icon
                      = material_icon.check_box
                  - elsif entry.entry_type == "EntryLine"
                    .tip-icon
                      = material_icon.font_download.css_class("normalize")

                  = link_to edit_diary_entry_path(entry), class: "edit" do
                    = material_icon.edit

                .clearfix

              .divider

        .entry-form
          = render "form"